import type { Metadata } from "next";
import "@/components/ui/globals.css";
import {lusitana} from "@/components/ui/fonts";
import NavBar from "@/components/ui/dashboard/navbar";



export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${lusitana.className} antialiased`}>
        <NavBar  />
        {children}
        </body>
        </html>
    );
}
